services:
  worker:
    container_name: worker
    image: openledgerhub/worker:1.0.0
    ports:
      - "8080:8080"
      - "5555:5555"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./keystore/keystore.json:/app/keystore.json
      - ./machineid.txt:/etc/machine-id:ro
    env_file:
      - .env
    networks:
      - worker-network
  scraper:
    container_name: scrapper
    image: openledgerhub/scraper:1.0.0
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - worker-network
    depends_on:
      - worker
networks:
  worker-network:
    name: worker-network